AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: A collection of utilities that integrate with Eventbrite

Parameters:
  EventbriteToken: { Type: String }

Resources:
  TicketNotificationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/ticket-notifications
      Description: >-
        Handles Eventbrite webhook requests and sends messages to Slack with
        information about ticket sales
      Environment:
        Variables:
          EVENTBRITE_TOKEN: !Ref EventbriteToken
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED
      Handler: index.handler
      MemorySize: 128
      Policies:
        - Statement:
            - Action: events:PutEvents
              Effect: Allow
              Resource: !Sub arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:event-bus/default
              Sid: AllowDefaultEventBusPut
            - Action: lambda:Invoke
              Effect: Allow
              Resource: !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:eventbrite-toolkit-TicketNotificationsFunction-*
              Sid: AllowSelfInvoke
          Version: "2012-10-17"
      Runtime: nodejs20.x
      Tags:
        prx:meta:tagging-version: 2021-04-07
        prx:cloudformation:stack-name: !Ref AWS::StackName
        prx:cloudformation:stack-id: !Ref AWS::StackId
        prx:ops:environment: Production
        prx:dev:application: Eventbrite Toolkit
      Timeout: 8
  TicketNotificationsLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: !Sub /aws/lambda/${TicketNotificationsFunction}
      RetentionInDays: 30
      Tags:
        - { Key: prx:meta:tagging-version, Value: "2021-04-07" }
        - { Key: prx:cloudformation:stack-name, Value: !Ref AWS::StackName }
        - { Key: prx:cloudformation:stack-id, Value: !Ref AWS::StackId }
        - { Key: prx:ops:environment, Value: Production }
        - { Key: prx:dev:application, Value: Eventbrite Toolkit }
  TicketNotificationsErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "MINOR [Eventbrite] Ticket Notifications <prod> EXPERIENCING ERRORS"
      AlarmDescription: >-
        The error rate on the Eventbrite toolkit activity Slack notifications
        Lambda function has exceeded 0. Some ticket activity may not be
        reaching Slack channels.
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref TicketNotificationsFunction
      EvaluationPeriods: 2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Tags:
        - { Key: prx:meta:tagging-version, Value: "2021-04-07" }
        - { Key: prx:cloudformation:stack-name, Value: !Ref AWS::StackName }
        - { Key: prx:cloudformation:stack-id, Value: !Ref AWS::StackId }
        - { Key: prx:ops:environment, Value: Production }
        - { Key: prx:dev:application, Value: Eventbrite Toolkit }
      Threshold: 0
      TreatMissingData: notBreaching
